### ISSUE TITLE
graphql import broken in Next.js since v2.1.0-alpha.1

### ISSUE THREAD

**Issue by jaydenseric** [apollographql/react-apollo#1591]
Importing `graphql` in a component in a Next.js project works in v2.1.0-alpha.0 but causes errors for all newer alpha and beta versions.

```js
import { graphql } from 'react-apollo'
```

<img width="634" alt="screen shot 2018-01-29 at 8 25 44 pm" src="https://user-images.githubusercontent.com/1754873/35502925-a5a9486a-0532-11e8-9e98-1963080e33d6.png">

I'm unsure if this is special to Next.js or if it is simply an issue for all Webpack users.

**Comment by jaydenseric** [comment]
Potentially related? https://github.com/apollographql/react-apollo/issues/1590

**Comment by chutiphon-k** [comment]
**ME TOO**

**Comment by binkpitch** [comment]
I got this too, is there any work around?

**Comment by edorivai** [comment]
This is not Next.js specific.

Running the following in node also fails:

```js
const apollo = require('react-apollo');

console.log(apollo.graphql); // logs "undefined"
```

**Comment by petetnt** [comment]
Pretty sure this was borked in https://github.com/apollographql/react-apollo/pull/1576 /  https://github.com/apollographql/react-apollo/commit/18939c21d97be71965c38e8f5cfb28d564b7bc6e

**Comment by vjpr** [comment]
```
var _reactApollo = require('react-apollo');
(0, _reactApollo.graphql) // {default: ..., renderToStringWithData: ...}
```

_react-apollo/index.js_

```
"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./browser"));
var renderToStringWithData_1 = require("./renderToStringWithData");
exports.renderToStringWithData = renderToStringWithData_1.renderToStringWithData;
//# sourceMappingURL=index.js.map
```

**Comment by pantharshit00** [comment]
Thanks for the workaround

Copy and paste ninjas there is a syntax error in the babelrc snippet get paste this snippet instead

```js
 "plugins": [
    [
      "module-resolver",
      {
        "alias": {
          "^react-apollo$": "react-apollo/index"
        }
      }
    ]
  ]
```

Thanks again @vjpr

**Comment by brandonmp** [comment]
hm. implementing the fix in post above creates all kinds of errors w/ `renderToStringWithData.js` and `react-dom`

anyone else hitting this?

error: 

```
ERROR in ./node_modules/react-apollo/renderToStringWithData.js
Module not found: Error: Can't resolve 'react-dom/server' in '/mnt/c/Users/brand/code/admitbrain/node_modules/react-apollo'
 @ ./node_modules/react-apollo/renderToStringWithData.js 3:15-42
 @ ./node_modules/react-apollo/index.js
 @ ./higher-order-components/withApollo.js
 @ ./pages/index.js
 @ multi ./pages/index.js
```

**Comment by pantharshit00** [comment]
@brandonmp @vjpr This is now fixed in next js. 

https://github.com/zeit/next.js/releases/tag/5.0.1-canary.2

**Comment by FredyC** [comment]
It's somewhat funny looking within a debugger :)

![image](https://user-images.githubusercontent.com/1096340/37472662-f0ee4f20-286c-11e8-93a6-3038f48ec315.png)

**Comment by wesbos** [comment]
I've tried the posted workaround and I still get this error:

```
Unexpected token export
/......../node_modules/react-apollo/index.js:1
(function (exports, require, module, __filename, __dirname) { export * from './browser';
                                                              ^^^^^^
```

Anyone have some insight to what is happening?

**Comment by pantharshit00** [comment]
@wesbos Hi I am one of your happy customers.

I too got those errors.
From my investigation there is no need of workaround now.

Stable react Apollo is compatible with next.

Your next version should be higher than next 5.0.1-canary2 . That fixes this message. I recommend the newly launched 5.1

And react Apollo version should be 2.1 or higher not any beta version.

This is a new project using both https://github.com/JesseRWeigel/javascript-af

**Comment by wesbos** [comment]
@pantharshit00 thank you - I tried upgrading to  Next 5.1 and the error persists :)

**Comment by wesbos** [comment]
pretty sure this can be closed

**Comment by rosskevin** [comment]
I'm pretty sure this was solved in July. If not ping me and I'll reopen.
