### ISSUE TITLE
GraphQL query throws 'QueryKeyMaker cannot handle circular query structures' with simple React Native setup

### ISSUE THREAD

**Issue by sammccord** [apollographql/react-apollo#2442]
I spun up a new expo app with `expo init`, added requisite React/GraphQL dependencies, and was greeted with this fun, unshakable error:

```
QueryKeyMaker cannot handle circular query structures
```

whenever any `<Query />` component is mounted.

**Intended outcome:**

I was attempting to query a public graphql endpoint from a simple `react-native` app, and see either data or a network error with the following dependencies.

`package.json` dependencies
```json
"dependencies": {
    "apollo-boost": "^0.1.16",
    "apollo-utilities": "^1.0.21",
    "babel-plugin-inline-import-graphql-ast": "^2.4.1",
    "expo": "^30.0.1",
    "graphql": "^14.0.2",
    "graphql-tag": "^2.9.2",
    "react": "16.3.1",
    "react-apollo": "^2.2.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz"
  }
```

```js
// apolloClient.js
export default new ApolloClient({
  uri: 'https://fakerql.com/graphql'
})

// App.js
export default class App extends React.Component {
  render () {
    return (
      <ApolloProvider client={apolloClient}>
        <Query />
      </ApolloProvider>
    )
  }
}

// query.js
const TEST = gql`
  query me {
    me {
      id
    }
  }
`

export default class TestQuery extends React.Component {
  render () {
    return (
      <Query query={TEST}>
        {({ loading, error, data }) => {
          console.log(loading, error, data)
          return <View />
        }}
      </Query>
    )
  }
}
```

**Actual outcome:**

The app compiles, and throws immediately with the following stack trace:

![QueryKeyMaker cannot handle circular query structures](https://i.imgur.com/XSRELth.jpg)

**How to reproduce the issue:**

I've published a minimal [example app](https://expo.io/@slowcodetochina/test) that crashes with the same error when pointed at a public graphql endpoint. [Here's](https://github.com/sammccord/QueryKeyMaker-issue-repo) the github repo, with instructions on how to reproduce locally.

It's occuring constantly on my OnePlus 6, with Android 9 Pie. Can't test on iOS (on linux), but would love to know if that happens there as well.

**Version**
- apollo-client@2.4.2
- react-apollo@2.2.3

**Comment by radiegtya** [comment]
same here

**Comment by SMJ93** [comment]
@FabioVerge hmmmmm looks like that could be the issue. I had a similar issue a few months back where Metro released a breaking change as a minor release which broke everything.

It looks like a dependency in the tree has been updated which doesn't support React Native Android 🙁

**Comment by Kasstorr** [comment]
Same setup here.
Yes, it's working in iOS Emulator while in Android it's not.
Looks like `apollo-cache-inmemory` it's filing the Error.

**Comment by SMJ93** [comment]
@sammccord did you run `npm install` after Friday last week?

**Comment by SMJ93** [comment]
@kasstorr does it work for you in Android debug mode? Also where does it mention `apollo-cache-inmemory`?

**Comment by Kasstorr** [comment]
> @Kasstorr does it work for you in Android debug mode? Also where does it mention `apollo-cache-inmemory`?

1) Yeah, it's working with the debug option
2) In the stack trace, in the expo app in my physical device, i tapped on the first report of the stack trace and opened a method of the `apollo-cache-inmemory` package (`apollo-cache-inmemory/lib/bundle.umd.js:219`).

**Comment by SMJ93** [comment]
Good spot! That package was also published 3 days ago:

https://www.npmjs.com/package/apollo-cache-inmemory

**Comment by SMJ93** [comment]
Setting the version in our package.json fixed the issue:

```
 "apollo-cache-inmemory":"1.2.9",
```

**Comment by Kasstorr** [comment]
> Setting the version in our package.json fixed the issue:
> 
> ```
>  "apollo-cache-inmemory":"1.2.9",
> ```

For me the error popped out moving to `apollo-boost` package, from single `apollo-client`, `apollo-cache-inmemory` and `apollo-link-http`. But going back to single packages solved the issue. My package.json's package versions:

```json
    "apollo-cache-inmemory": "^1.2.10",
    "apollo-client": "^2.4.2",
    "apollo-link-http": "^1.5.5",
```

**Comment by SMJ93** [comment]
Nice 👍  

Looks like the latest version of `apollo-cache-inmemory` is the issue. Hardcoding the version should fix it!

**Comment by benjamn** [comment]
Please try the latest version of `apollo-cache-inmemory` (1.3.3) when you have a chance, since I believe https://github.com/apollographql/apollo-client/commit/db0ce68bc12d2e57e95b146bbea99ca3921894af will help with this issue:
```bash
npm install apollo-cache-inmemory@next
```
Specifically, the `QueryKeyMaker` still complains if it encounters circular query structures, but it's more careful now about which subfields it traverses, so it shouldn't get confused by stray metadata properties that happen to contain circular references.

As a side note, I was not actually able to reproduce the problem (though I very much appreciate the runnable reproduction!), so it would be very helpful if anyone can shed some light on the circular references in question. Are they present in the AST document returned by the `graphql-js` parser or the `gql` template tag? Or are they added at some later point in the React Native pipeline?

There's definitely more that we can do here to tolerate/prevent circular references; it's just a matter of diagnosing the underlying causes and weighing possible solutions.

**Comment by gabceb** [comment]
Cheers @benjamn. Just bumped into this on a new app that we have and I am now getting the error below (like most folks above crashes on Android but not on iOS). It looks like the issue comes from the facebook Map.js polyfill when we are trying to `.get` on the cache. When I move down to the latest version (1.2.10) I see the `QueryKeyMaker`  circular issues but when I move to `1.3.3-beta5` and above including `1.3.3` it switches to this error:

![image](https://user-images.githubusercontent.com/470852/46386532-f18d6a80-c68f-11e8-88d2-936a6e8c981d.png)

**Comment by gabceb** [comment]
Like most other folks downgrading to `1.2.9` fixes the issue

**Comment by sammccord** [comment]
@benjamn Thanks for looking into this. `1.3.3` still appears to throw for me, while locking to `1.2.9` works fine. I'm not convinced this has anything to do with the structures being queried since in the initial example I posted, it was throwing when only a primitive was requested in the query.

**Comment by benjamn** [comment]
@gabceb While I still find it astonishing that the authors of the React Native `Map` and `Set` polyfills thought they could get away with simply not supporting non-extensible object keys, I've devised this (pretty clever, IMO) workaround to treat the symptoms: https://github.com/apollographql/apollo-client/pull/3964/commits/833072ee11a3c06f7d83964faae02e157f272dfb

Try it out in `apollo-cache-inmemory@1.3.4` when you get a chance!

**Comment by benjamn** [comment]
@sammccord Any chance you can connect a debugger to your repro app and set breakpoints in [the `QueryKeyMaker` code in question](https://github.com/apollographql/apollo-client/blob/07f3f479feea3e6c505b083f6f3fbf747965495e/packages/apollo-cache-inmemory/src/queryKeyMaker.ts#L40)? Since I haven't been able to reproduce the problem myself, I'm hoping to find out which `value` is causing a cycle. If you look at the call stack, you should also be able to determine the sequence of properties that lead from the original `DocumentNode` to that object.

**Comment by gabceb** [comment]
@benjamn 1.3.4 puts me back on circular QueryKeyMaker. See the output for the `value` and `cached` vars

value

```javascript
{ selectionSet: 
    { selections: 
       [ { selectionSet: undefined,
           directives: [],
           arguments: [],
           name: { value: 'timesheetId', kind: 'Name' },
           alias: undefined,
           kind: 'Field' },
         { selectionSet: undefined,
           directives: [],
           arguments: [],
           name: { value: 'employerId', kind: 'Name' },
           alias: undefined,
           kind: 'Field' },
         { selectionSet: undefined,
           directives: [],
           arguments: [],
           name: { value: 'weekEnding', kind: 'Name' },
           alias: undefined,
           kind: 'Field' },
         { selectionSet: 
            { selections: 
               [ { selectionSet: undefined,
                   directives: [],
                   arguments: [],
                   name: { value: 'fullName', kind: 'Name' },
                   alias: undefined,
                   kind: 'Field' },
                 { selectionSet: undefined,
                   directives: [],
                   arguments: [],
                   name: { value: 'avatarUrl', kind: 'Name' },
                   alias: undefined,
                   kind: 'Field' },
                 { kind: 'Field', name: { kind: 'Name', value: '__typename' } } ],
              kind: 'SelectionSet' },
           directives: [],
           arguments: [],
           name: { value: 'contact', kind: 'Name' },
           alias: undefined,
           kind: 'Field' },
         { selectionSet: 
            { selections: 
               [ { selectionSet: undefined,
                   directives: [],
                   arguments: [],
                   name: { value: 'shiftId', kind: 'Name' },
                   alias: undefined,
                   kind: 'Field' },
                 { selectionSet: undefined,
                   directives: [],
                   arguments: [],
                   name: { value: 'forecastCharge', kind: 'Name' },
                   alias: undefined,
                   kind: 'Field' },
                 { selectionSet: undefined,
                   directives: [],
                   arguments: [],
                   name: { value: 'jobTitle', kind: 'Name' },
                   alias: undefined,
                   kind: 'Field' },
                 { selectionSet: undefined,
                   directives: [],
                   arguments: [],
                   name: { value: 'name', kind: 'Name' },
                   alias: undefined,
                   kind: 'Field' },
                 { selectionSet: undefined,
                   directives: [],
                   arguments: [],
                   name: { value: 'timeRange', kind: 'Name' },
                   alias: undefined,
                   kind: 'Field' },
                 { selectionSet: undefined,
                   directives: [],
                   arguments: [],
                   name: { value: 'startDate', kind: 'Name' },
                   alias: undefined,
                   kind: 'Field' },
                 { selectionSet: undefined,
                   directives: [],
                   arguments: [],
                   name: { value: 'endDate', kind: 'Name' },
                   alias: undefined,
                   kind: 'Field' },
                 { selectionSet: 
                    { selections: 
                       [ { selectionSet: undefined,
                           directives: [],
                           arguments: [],
                           name: { value: 'type', kind: 'Name' },
                           alias: undefined,
                           kind: 'Field' },
                         { selectionSet: undefined,
                           directives: [],
                           arguments: [],
                           name: { value: 'date', kind: 'Name' },
                           alias: undefined,
                           kind: 'Field' },
                         { selectionSet: undefined,
                           directives: [],
                           arguments: [],
                           name: { value: 'comment', kind: 'Name' },
```

cached:

```javascript
{}
```

**Comment by benjamn** [comment]
@gabceb Thanks!

That expansion of `value` seems like it got cut off, though. If `value` is circular, that's because it contains itself at some point, so I'd like to know where that happens. So far it just looks like an ordinary tree.

What happens if you try `JSON.stringify(value)` in the debugger (it should throw an error about circular references)?

**Comment by gabceb** [comment]
@benhjames `value` updated on the comment above. I stringified right inside the if statement when the cicular reference is detected

**Comment by gabceb** [comment]
Re: your first question, I am running on a Android simulator on dev which means the js will actually be bundled on the machine using node but executed on the device using whatever js runtime. Yesterday I did see the non-extensible issue on a device running a prod build but have not tried on this new version. Looking into your second question.

**Comment by gabceb** [comment]
@benjamn See https://gist.github.com/gabceb/7a33b0769d05cfffa1a4941d07c81e91 for all the `key` variables on a `console.log` in this piece of code:

```javascript
PerQueryKeyMaker.prototype.lookupObject = function (object) {
            var _this = this;
            var keys = safeSortedKeys(object);
            var values = keys.map(function (key) {
                console.log("KEY", key);
                return _this.lookupAny(object[key]);
            });
            return this.cacheKeyRoot.lookup(Object.getPrototypeOf(object), this.cacheKeyRoot.lookupArray(keys), this.cacheKeyRoot.lookupArray(values));
        };
```

Note that there is a single `Query` element on the codebase (I had more but removed them to make debugging easier)

**Comment by thegreatgabsby** [comment]
got rid of apollo-boost and moved to single packages although the ```apollo-cache-inmemory``` 1.2.10 still crashes, so downgraded to 1.2.9

**Comment by benjamn** [comment]
@thegreatgabsby This issue refers to code added in `apollo-cache-inmemory@1.3.0` and later, so any difference between 1.2.10 and 1.2.9 should be discussed in a different issue (which you should feel free to open).

As a more general note, `apollo-cache-inmemory@1.3.0` added almost 100 commits over five months of work (see https://github.com/apollographql/apollo-client/pull/3394), so the observation that downgrading to 1.2.x fixes the problem is not as helpful as it would usually be, since the problem has so many possible places to hide. While downgrading is the recommended workaround for this problem, it's not the solution. If you'd like to help solve this problem, so that you (and everyone else) can safely reap the substantial performance improvements in 1.3.x, please feel free to try the reproduction and see if you can figure out what's going wrong in the `QueryKeyMaker` on Android.

**Comment by Vitiell0** [comment]
We were running into this issue as everyone else but downgrading to `apollo-cache-inmemory@1.2.9` in our package.json was not working. 

Found out this was caused because we were still using `apollo-client-preset` which uses `apollo-cache-inmemory@1.3.0`.

`apollo-client-preset` is deprecated so we removed it and it's now working using `apollo-cache-inmemory@1.2.9` in package.json

**Comment by carllippert** [comment]
@benjamn I upped to 1.3.4 to try and fix the circular query structures issue. No luck. Anything  I can give you to help diagnose?

**Comment by benjamn** [comment]
Exciting news! This issue turned out to be due to some nasty bugs in the React Native `Map` polyfill, which I have submitted a PR to fix: https://github.com/facebook/react-native/pull/21492. This is my first React Native PR, but I have complete confidence they'll review and merge it quickly.

In other words, this is entirely _not_ my fault, and entirely the fault of some folks who thought it would be a good idea to roll their own implementation of the ECMAScript `Map` container, even though there are multiple well-tested alternatives already available.

If I'm being honest: I'm not feeling so great right now about the profession we've chosen. How does software even work, like, ever, at all?

**Comment by gabceb** [comment]
Who says software works? I guess you didnt know is just a bunch of leprechauns showing things on screens 😁

Awesome work @benjamn 👏🏻

**Comment by benjamn** [comment]
Ok, if you update to `apollo-cache-inmemory@1.3.5`, this problem should be fixed!

**Comment by SMJ93** [comment]
Thanks @benjamn great work 👏
